### ISSUE TITLE
Emit error when struct is using infinite size

### ISSUE THREAD

**Issue by franklinsch** [flintlang/flint#116]
This is a subtask of #106.

**Comment by franklinsch** [comment]
If a struct `T` contains a property which (directly or indirectly) refers a value of type `T`, it uses an infinite amount of memory, and an error should be emitted.

**Comment by vietlq** [comment]
Do you have example code and stuff like logs that lets you know that you used *an infinite amount of memory*?

**Comment by franklinsch** [comment]
This Flint program currently causes the compiler to segfault: https://github.com/franklinsch/flint/blob/master/examples/invalid/infinite-structs.flint

**Comment by vietlq** [comment]
So Flint does not support recursive types and should detect & return error on those cases, right? I assume that there will not be data structures like linked-list in Flint, right?

**Comment by franklinsch** [comment]
Yes, at the moment, Flint doesn't support recursive types. They can be supported in the future if needed. For now, an error should be produced.

**Comment by vietlq** [comment]
I haven't read the code yet so I'd raise a quick question: Do you keep a directed graph of type dependencies? If yes, we could detect loops quickly and abort parsing.

**Comment by franklinsch** [comment]
Such a graph can easily be generated using the information already collected during parsing (represented in `Environment.swift`). The parser generates an AST, and multiple passes are performed over it (including `SemanticAnalyzer` and `TypeChecker`). I think this error should be produced in the `SemanticAnalyzer` phase. When visiting a struct declaration, the type dependency graph could be used to detect loops.

Just for context:
In `SemanticAnalyzer.struct`, `process(structDeclaration:passContext:)` will be called when visiting the `StructDeclaration` node, and `postProcess(structDeclaration:, passContext:)` will be called once the members of the structs have been visited. When visiting the AST, the `passContext` struct records information it collects during the visit.

**Comment by DJRHails** [comment]
Recommend closing as PR #229 fixed this
