### ISSUE TITLE
Support `size` member variable for arrays

### ISSUE THREAD

**Issue by franklinsch** [flintlang/flint#122]

**Comment by bearbin** [comment]
The length of dynamically sized arrays is not currently set, and there is no obvious method by which this would be achieved - to solve this would really be an identical problem to #257.

Effectively "dynamic arrays" as currently implemented are just dictionaries with integer keys - my feeling would be remove them as confusing duplication and add iteration over dictionaries as currently planned. (The iteration over DSAs in #242 does not work presently in any case, there would be no regression in features).

**Comment by bearbin** [comment]
The above comment is wrong - the length of DSAs is actually updated currently. Any access (read or write) with index of size is valid and increments the size to be size+1.
