### ISSUE TITLE
Add formal EBNF syntax for Flint

### ISSUE THREAD

**Issue by vietlq** [flintlang/flint#170]
References from JSON:
* https://en.wikipedia.org/wiki/Extended_Backus–Naur_form
* https://www.json.org
* https://github.com/cierelabs/yaml_spirit/blob/master/doc/specs/json-ebnf.txt

I can help with this one :) It will be very useful for have formal EBNF syntax specification as we can use that to develop independent implementations. I want to develop one in JS or ReasonML/OCaml and compile to JS and then have a similar playground like Remix https://remix.ethereum.org or https://reasonml.github.io/en/try.html for people to learn & deploy quickly.

Developing a parser and syntax highlighter for Flint in JS would be a piece of cake when using this tool: https://nearley.js.org

Use this tool for syntax diagram generation: http://www.bottlecaps.de/rr/ui

**Comment by franklinsch** [comment]
The Flint grammar is specified here:
https://github.com/franklinsch/flint/blob/master/docs/grammar.txt

It's not exactly EBNF, but close.

**Comment by vietlq** [comment]
Nice. I will convert to EBNF and play with Nearley to parse the current files :)

**Comment by franklinsch** [comment]
Flint compiles to IULIA bytecode, which can be embedded in a Solidity file.
As described in the [Language Guide](https://franklinsch.gitbooks.io/flint/content/deploying-a-smart-contract.html), Flint code can already be used in Remix and with Truffle already.

However, features such as line-by-line debugging wouldn't be possible. I'm not a fan of compiling Flint to JS. Rather than building a web-based IDE/playground, I think a binary application is better suited for debugging. It would allow to interact with the bytecode itself (which is what will actually be deployed to Ethereum), rather than a JS version—which is not guaranteed to be equivalent to the bytecode.

**Comment by franklinsch** [comment]
Please make a PR once you have an EBNF! :)

**Comment by vietlq** [comment]
Thanks for the link. I will start with EBNF first. I'm not very familiar with Swift. As Flint is still fresh, I think that having a tool to convert Solidity to Flint would be more useful than writing a new Flint compiler at the moment :) When the language is more mature, I think then we could have another Flint compiler implementation. I would be happy to learn more about Swift and contribute to the project :)

**Comment by franklinsch** [comment]
Swift is easy to pick up, and its type system has some nice features—which a lot of my OCaml friends like. I'd recommend trying it out! A Solidity to Flint compiler would be useful but I think would be challenging!

I'm glad you'd like to contribute to the Flint compiler! I think a good start issue would be https://github.com/franklinsch/flint/issues/116. Let me know if I can help!

**Comment by vietlq** [comment]
Hehe, you are right. I realised Flint compiles to Solidity and compiling Solidity to Flint is going backward. It won't be possible until standard library, structs in Solidity are done properly.

**Comment by vietlq** [comment]
@franklinsch What is `branch-statement`? Thanks. Also I found that `generic-argument-list` should be `generic-parameter-list`

```
// Statements

statements -> statement (statements)
statement -> expression
statement -> [return] (expression)
statement -> branch-statement
```

**Comment by franklinsch** [comment]
`branch-statement` should be `if-statement`, and you are right about `generic-argument-list`. I think the other way around is better though, i.e. `generic-parameter-list` should actually be `generic-argument-list`.

Thank you for spotting that! Please feel free to submit a PR, otherwise I can do it as well.

**Comment by vietlq** [comment]
Sure I will create a PR :)

**Comment by vietlq** [comment]
I have a few questions:

* What's the delimiter between the statements? `\n` and `\r\n`? It's quite unclear from `statements -> statement (statements)`
* Do you plan to have keywords for built-in types like `uint/uint256/bytes32` ... etc?
* Do parentheses in the grammar.txt mean optional? See: `(else-clause)`

Thanks.

**Comment by vietlq** [comment]
So as we discussed in https://github.com/franklinsch/flint/pull/192

```
variable-declaration -> "var" identifier type-annotation ("=" expression)
```

Should be changed to:

```
variable-declaration -> "var" identifier type-annotation "=" expression
```

**Comment by franklinsch** [comment]
The delimiter between statements in `\n`. Although I believe the compiler supports `\r\n`, too. If you have arguments as to why it should be `\r\n`, I'd be happy to hear them.

Low-level types will not be accessible by the user directly. They can be dangerous to use. Flint's `Int` type will have safe wrap-around semantics.

Yes, the parenthesis mean optional.

Hope that helps!

**Comment by franklinsch** [comment]
I replied in #192 :)

**Comment by vietlq** [comment]
Thanks. I will support both `\n` and '\r\n' too. There are too many Windows to ignore ;)

**Comment by vietlq** [comment]
Please enlighten me more about Flint `Int` built-in type and how they can provide safety compared to myriads of `uintXX`? Thanks :D

**Comment by vietlq** [comment]
Work is being done slowly here: https://github.com/vietlq/flint/tree/scratch/add-nearley-parser
