### ISSUE TITLE
Support fallback function mechanism

### ISSUE THREAD

**Issue by franklinsch** [flintlang/flint#174]

**Comment by DJRHails** [comment]
- [ ] Fallback function must be simple [Consensys Recommendations](https://consensys.github.io/smart-contract-best-practices/recommendations/#favor-pull-over-push-for-external-calls). Linters often restrict it to 2 statements

**Comment by DJRHails** [comment]
### What if I really want a complex fallback
#### Code Audits
Another possible way to use the unsafe method "address.call.value()()", but only use certain functions that you can trust won't deplete the gas. ie, depending on the system: develop a function called "safeSend(uint _wei)" which maps to a specific bytecode. This audited signature is first checked (say with getCode) to see if it exists in the bytecode. [Sidenote: address.code is planned to be implemented in Solidity, so this will make it possible].

This is preliminary, and more in depth explorations will need to be done. Potential additional services is to use reputation systems + registries to basically ask a contract: "is this safe?" before executing the code.

#### Oracles
When using send(), you basically have enough gas to log that it received money. When this happens an oracle can pick up this action and re-issue a transaction, supplying it with gas to essentially "keep going".
