### ISSUE TITLE
Warn on identifiers not following style conventions

### ISSUE THREAD

**Issue by DJRHails** [flintlang/flint#243]
For security and ease of legibility we (@bearbin and I) were considering warnings if you aren't following naming conventions.

Throughout flint code and the standard library, _variables_ are camelCase, _types_ are SentenceCase and (possibly) _states_ are CAPITALS.

Given the focus on Flint as being a language which doesn't allow you to make think through decisions (e.g. forcing you to explicitly type any for caller capabilities, or add mutating to functions that change contract variables) we felt this might be in keeping with it's philosophy.

**Comment by bearbin** [comment]
We decided that this was a bad idea and users should be trusted to use their own style conventions.
