### ISSUE TITLE
Parameters should be let constants not variables.

### ISSUE THREAD

**Issue by DJRHails** [flintlang/flint#324]
Having function parameters be variables has limited utility, optimizing for a line of code at the cost of confusion with inout and leading to code that can appear to do mutate the parameter while really mutating a local copy. 

To emphasize the fact these values are unique copies and don't have the write-back semantics of inout, we should not allow parameters to be mutated.

If mutation of a function parameter is desired then the following can be used:
```
func foo(i: Int) {
  var i = i
}
```
However, this shadowing is not necessarily an ideal fix and may indicate an anti-pattern.

**Comment by bearbin** [comment]
Parameters to functions?

**Comment by DJRHails** [comment]
Exactly so: 
```
func test(a: Int, b: Address) {
  a += 2 // Compile error as a is a constant
}
```
