### ISSUE TITLE
`forall` causes internal error

### ISSUE THREAD

**Issue by wmanshu** [flintlang/flint#437]
Take the simplest example, in the Marking.flint program(in the valid folder), if we add such a verification to the *assignGrade* function:
```
public func assignGrade(student: Address, grade: Int)
    mutates (grades)
    post (forall (a: Address) :: (grades[a] == prev(grades[a]) || (a == student && grades[a] == grade)))
  {
    grades[student] = grade
  }
```
it gives a error when compiling, the error massage is just : 
> Internal Error has occured
ERROR
Failed to compile.

**Comment by mrRachar** [comment]
It doesn't appear that this was implemented at all and is actually closer to Boogie than Flint. The verifier seemed to be limited to only allowing you to do `arrayEach(x, xs, p)`. The recent [matteobilard/flint/PR#4](https://github.com/matteobilardi/flint/pull/4) should provide a fix to this, by introducing new typed quantifiers to the verifier, seeming to work well so far. This should be merged upstream soon, the next time that [matteobilardi/flint](https://github.com/matteobilardi/flint) is stable enough to be merged.
