### ISSUE TITLE
Get contract using address

### ISSUE THREAD

**Issue by wmanshu** [flintlang/flint#473]
In solidity, it is possible to get contract using the address of contract. Is it possible to also do that in Flint?

solidity code example:
```
function verifyInput(address applicantContract) notExpired notClaimed public
    {
        //instantiate the applicants solution attempt
        //check it outputs the correct solution
        MachineLearningSolutionAttempt mlAttempt;
        mlAttempt = MachineLearningSolutionAttempt(applicantContract);
        var (output, applicant) = mlAttempt.model(modelData);
        bytes32 hashOfValue = keccak256(abi.encodePacked(output));
        bytes32 hashOfCorrectOutput = keccak256(abi.encodePacked(modelData));
        if(hashOfValue == hashOfCorrectOutput)
        {
            claimed = true;
            winningContract = applicantContract;
            applicant.send(this.balance);
        }
    }
```

from [https://github.com/James-Sangalli/learn-solidity-with-examples/blob/master/Verification/MachineLearningVerification.sol](url)

**Comment by mrRachar** [comment]
Getting other contracts can be done through [external traits](https://docs.flintlang.org/docs/language_guide#creating-an-instance). In the future, you might find it much quicker if you try to find the answers you're looking for in the documentation
