### ISSUE TITLE
Add keys property to Dictionary

### ISSUE THREAD

**Issue by franklinsch** [flintlang/flint#67]

**Comment by DJRHails** [comment]
Dictionary would be a standard library struct: with a runtime representation, and a associated array with the keys in.

**Comment by bearbin** [comment]
I am now investigating solving this issue

**Comment by DJRHails** [comment]
If you can add dictionaries as a caller capability using the keys array that would be great :+1:

**Comment by bearbin** [comment]
This was resolved in PR #274
